### ISSUE TITLE
Add support for First Alert Smoke / Carbon Monoxide Detector

### ISSUE THREAD

**Issue by humac** [pdlove/homebridge-smartthings#11]
[SmartThings] Device Skipped - Group unknown, Name 1st Floor Smoke Alarm, ID <ID>, JSON: {"name":"1st Floor Smoke Alarm","deviceid":"<ID>","capabilities":{"Battery":1,"Smoke Detector":1,"Carbon Monoxide Detector":1,"Sensor":1},"commands":{},"attributes":{"battery":100,"smoke":"clear","carbonMonoxide":null,"alarmState":"clear"}}

**Comment by humac** [comment]
I see you added support for smoke and CO.  I updated everything to try the latest code but I still get the Device Skipped message.

**Comment by coolcom** [comment]
I am getting:
`[SmartThings] Device Skipped - Group unknown, Name Office Smoke/CO, ID 10aea05a-c07a-446b-a6c1-a002f89ce85a, JSON: {"name":"Office Smoke/CO","deviceid":"10aea05a-c07a-446b-a6c1-a002f89ce85a","capabilities":{"Battery":1,"Smoke Detector":1,"Carbon Monoxide Detector":1,"Sensor":1},"commands":{},"attributes":{"battery":83,"smoke":"clear","carbonMonoxide":null,"alarmState":"clear"}}
`
for this as well.

**Comment by pdlove** [comment]
Please verify this is now working.

**Comment by humac** [comment]
With SmartApp v0.3.6 i'm still getting:

[SmartThings] Device Skipped - Group unknown, Name 1st Floor Smoke Alarm, ID f3bb46bf-bc59-45af-a132-b3dc57605506, JSON: {"name":"1st Floor Smoke Alarm","deviceid":"f3bb46bf-bc59-45af-a132-b3dc57605506","capabilities":{"Battery":1,"Smoke Detector":1,"Carbon Monoxide Detector":1,"Sensor":1},"commands":{},"attributes":{"battery":99,"smoke":"clear","carbonMonoxide":null,"alarmState":"clear"}}
[SmartThings] Unknown Capabilities: ["Smoke Detector","Carbon Monoxide Detector"]

**Comment by coolcom** [comment]
I will check tomorrow and let you know.

**Comment by humac** [comment]
Problems with v 0.4.0 so I can't test with it.

**Comment by pdlove** [comment]
Try now. You guys are really good about updating. I've made a note on another post that I'll be doing no more major changes to the smart app. It now has everything needed to do all the awesomeness I had in mind for the plugin in the near future.

**Comment by humac** [comment]
On version 0.4.1 of SmartApp and npm version 0.3.5 still getting device skipped:

[SmartThings] Device Skipped - Group unknown, Name 1st Floor Smoke Alarm, ID f3bb46bf-bc59-45af-a132-b3dc57605506, JSON: {"name":"1st Floor Smoke Alarm","deviceid":"f3bb46bf-bc59-45af-a132-b3dc57605506","capabilities":{"Battery":1,"Smoke Detector":1,"Carbon Monoxide Detector":1,"Sensor":1},"commands":{},"attributes":{"battery":99,"smoke":"clear","carbonMonoxide":null,"alarmState":"clear"}}
[SmartThings] Unknown Capabilities: ["Smoke Detector","Carbon Monoxide Detector"]

**Comment by pdlove** [comment]
Thanks for testing. I'll add a virtual smoke detector to mine and try to determine why it isn't behaving as expected.

**Comment by humac** [comment]
No Problem

**Comment by pdlove** [comment]
It looks like I had the smoke detector logic wrapped in the Thermostat by mistake. Let me know if it works now.

**Comment by coolcom** [comment]
Device Skipped - Group unknown, Name Office Smoke/CO, ID 10aea05a-c07a-446b-a6c1-a002f89ce85a, JSON: {"name":"Office Smoke/CO","deviceid":"10aea05a-c07a-446b-a6c1-a002f89ce85a","capabilities":{"Battery":1,"Smoke Detector":1,"Carbon Monoxide Detector":1,"Sensor":1},"commands":{},"attributes":{"battery":82,"smoke":"clear","carbonMonoxide":null,"alarmState":"clear"}}

**Comment by coolcom** [comment]
It's possible I don't have an updated npm version? How do I update that? I did an` $npm update` but it returned nothing.

**Comment by pdlove** [comment]
I use "npm update -g homebridge-smartthings"
It should display "homebridge-smartthings@0.4.1" unless there isn't anything to do.

**Comment by jcharr1** [comment]
I updated to npm homebridge-smartthings a little while ago (for some reason I had to uninstall and reinstall to get the latest version) and now homebridge crashes on startup when trying to add my 2 First Alert Smoke/CO detectors:

`/Users/jason/.node/lib/node_modules/homebridge-smartthings/accessories/smartthings.js:193
        thisCharacteristic = this.getService(Service.SmokeSensor).getCharacteristic(Characteristic.SmokeDetected)
                                                                 ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at new SmartThingsAccessory (/Users/jason/.node/lib/node_modules/homebridge-smartthings/accessories/smartthings.js:193:66)
    at populateDevices (/Users/jason/.node/lib/node_modules/homebridge-smartthings/index.js:57:19)
    at /Users/jason/.node/lib/node_modules/homebridge-smartthings/index.js:75:4
    at /Users/jason/.node/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/Users/jason/.node/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)`

I'm also running v0.4.1 of the smart app. If I deselect the detectors in the smart app then homebridge starts up just fine. This is running on a 2011 Mac Mini running OSX 10.11.3. Some more npm version info:

`npm list -g | grep homebridge
├─┬ homebridge@0.2.17
├─┬ homebridge-nest@1.0.1
├── homebridge-smartthings@0.4.1`

**Comment by washchuk** [comment]
I can confirm the same error message jcharr1 listed in version 0.4.1. With smoke detectors enabled, homebridge crashes before it finishes initializing. If I disable the smoke detectors in the JSON Complete API app, I can run homebridge without issue.

**Comment by pdlove** [comment]
I've updated github to correct this. I'll go ahead and publish as well since the othe serious error is relate to the specific users' node installs.

**Comment by coolcom** [comment]
I don't see any updates to github, but as of right now, if I have my first alert smoke/CO added, homebridge does not start and throws error.

**Comment by kenthua** [comment]
I have this same issue.  Is this going to require an npm update 0.4.1+ or smartapp update to homebridge-smartthings

**Comment by pdlove** [comment]
I just published 0.4.2 of homebridge-smartthings. It should work with that one.

**Comment by jcharr1** [comment]
That fixed it for me. Thanks. :)

**Comment by humac** [comment]
I see it added but I still see "Smoke Detector","Carbon Monoxide Detector" listed as unknown capabilities in the logs.  Also it is labeled as a "Smoke" in the idevices and eve apps. Can it be changed to "Alert" or "Smoke/CO" detected in the apps?

SmartThings] Device Added - Group shades, Name Living Room Upper Shades, ID 587afb93-2017-4cee-b9b3-86186cc110ae
[SmartThings] Device Added - Group detectors, Name 1st Floor Smoke Alarm, ID f3bb46bf-bc59-45af-a132-b3dc57605506
[SmartThings] Unknown Capabilities: ["Window Shade",**"Smoke Detector","Carbon Monoxide Detector"**]
[SmartThings] Initializing platform accessory 'Living Room Upper Shades'...
[SmartThings] Initializing platform accessory '1st Floor Smoke Alarm'...

**Comment by pdlove** [comment]
Smoke and CO are two different services in HomeKit, so you should see one for each that is called "1st Floor Smoke Alarm"

**Comment by humac** [comment]
I only see smoke there is nothing indicating CO

**Comment by kenthua** [comment]
After applying the update i now see co and smoke options, which I think is what is expected.

Sent from mobile




On Fri, Feb 19, 2016 at 7:48 PM -0800, "Huy Nguyen" <notifications@github.com> wrote:












I only see smoke there is nothing indicating CO

**Comment by humac** [comment]
I'm using the v 0.4.2 of plugin and 0.4.1 of the smart app

**Comment by coolcom** [comment]
I only see smoke as well, nothing about CO.

**Comment by humac** [comment]
It's odd i have 3 first alert model zcombo smoke / co detectors and only one of them has both smoke and co while the other are only showing smoke in HomeKit

**Comment by humac** [comment]
@coolcom today I noticed that my 2nd floor detector started to show CO in homebridge-smartthings plugin.  Add realized that i pushed the test button today to test it out with Smartthings.  Then I tested the theory out and went to my 3rd detector, it wasn't appearing in homekit via this plugin, so I pushed the test button on the detector and restarted homebridge and voila it appeared in homekit. :)

So now all my detectors are reporting smoke and co to homekit.

**Comment by pdlove** [comment]
@coolcom @humac Can you confirm this is working?

**Comment by humac** [comment]
It is working for me both smoke and CO are now showing in HomeKit when homebridge and the smartthings plugin are working.  I'm testing new plugin 4.6 right now but am having a hard time getting Eve app to see homebridge at the moment.  Will report back once I get it working.

**Comment by pdlove** [comment]
Thank you. I feel really good that the lingering issues are resolved. I've always had the goal of not having to restart home bridge... ever... well, except for software updates.

**Comment by humac** [comment]
Got 0.4.6 of the plugin working had to clear the persist folder.  Confirm I see both Smoke and CO.  For CO to appear I had to run a manual test at each detector and then CO appeared in homekit.

**Comment by pdlove** [comment]
Sounds good. This should have the persist folder issue resolved where you don't have to clear it any more.

**Comment by dedtees** [comment]
Hi all, not sure if this applies to this thread, but hoping for some direction. I have received two false alerts from the smoke alarm/co via smart things hub and my suspicions tell me it was just trying to say it was a battery issue. Would this code work to resolve that? Thanks eric

**Comment by pdlove** [comment]
Did you have the false alarms actually in smart things? If so, there isn't anything in homebridge-smartthings that would help.

**Comment by dedtees** [comment]
Smartthings sent me the alert. I thought maybe the smoke alarm sent a low battery message that is being interpreted as a smoke alarm to Smartthings since there was no issue with either smoke or co. This is a 2nd time it's happened with two different smoke/co alarms. I also think Smartthings doesn't pull the correct battery life on a consistent basis. If I look it won't have polled the alarm for months.
