### ISSUE TITLE
Virtual Switches not available in JSON app

### ISSUE THREAD

**Issue by mishakim** [pdlove/homebridge-smartthings#22]
I'm not seeing any of my virtual switches (using the built-in "simulated switch" device type) in the JSON Complete API smart app. They were in the old JSON API app. They're useful for triggering Rule Machine to do things that homebridge can't do on its own due to lack of support in HomeKit.

**Comment by pdlove** [comment]
Please confirm that SmartApp version 0.3.5 allows selection and usage of the Simulated Switch.

**Comment by mishakim** [comment]
Yep, they're there now

Misha

**Comment by humac** [comment]
Since 0.3.5 nothing works for me as far as switches go that is.  None of my switches (real and virtual) I tested with 0.3.5 work and I get an error on line 181 in the ST IDE logs I reverted back to the last working version which was 0.3.2.

This is the error I see with 0.3.5
024155ef-e57f-48e7-9145-0de5550946d6  9:28:15 PM EST: error groovy.lang.MissingPropertyException: No such property: result for class: script14553304952321035419627
Possible solutions: request @ line 181
024155ef-e57f-48e7-9145-0de5550946d6  9:28:13 PM EST: error Device Not Found

**Comment by pdlove** [comment]
line 181 is an odd spot. Tomorrow, I'll fix error trapping in my new work and we'll see if that resolves it.

**Comment by pdlove** [comment]
@Humac I think I have your issued fixed. I still need to add some better error traps so I haven't incremented the version yet.

**Comment by humac** [comment]
Nope now get the following error when i install this version with Physical and Virtual switches:

024155ef-e57f-48e7-9145-0de5550946d6  7:53:31 AM EST: error Device Not Found
024155ef-e57f-48e7-9145-0de5550946d6  7:53:31 AM EST: info Command Request
024155ef-e57f-48e7-9145-0de5550946d6  7:53:28 AM EST: error physicalgraph.app.exception.SmartAppException: Device not found @ line 182

**Comment by pdlove** [comment]
Are you using the latest plugin from github or npm?

**Comment by humac** [comment]
Using homebridge-smartthings@0.0.2 i did an "npm update -g homebridge-smartthings" so I think I'm on the latest

**Comment by mishakim** [comment]
I'm getting the same error: groovy.lang.MissingPropertyException: No such property: result for class: script14553805483941035419627
Possible solutions: request @ line 181
and none of my switches, real or virtual, are responding. 
Using latest plugin 0.0.2 from npm and smart app 0.35 from github

**Comment by pdlove** [comment]
Please verify all of this is working with plugin 0.3.5 from nam and smart app 0.3.6 (and 0.4.0 being released today)

**Comment by mishakim** [comment]
It appears to be working, with one in consequential error. Here's what the log shows (switch is "cats s", a rule "Cats T" responds to it. It's possible that error is coming from Rule Machine.  My other two virtual switches control speakers in the baby's room, so can't test those till morning.

`4a022b80-0a1a-4e29-a50c-310b7131f959  8:49:34 PM EST: info Update Cats T: Update cats s switch off
312736a1-2c67-4d48-9650-eb0208ca31a7  8:49:35 PM EST: error org.hibernate.AssertionFailure: collection [physicalgraph.location.Location.modes] was not processed by flush() @ line 1282
95d99cb0-bd6e-463f-bb4d-60a4c6c6165c  8:49:32 PM EST: info Command Successful for Device Update cats s, Command off
95d99cb0-bd6e-463f-bb4d-60a4c6c6165c  8:49:32 PM EST: info Command Request
d0b9ded7-c712-418b-af91-bd70921dc11f  8:49:32 PM EST: debug PUBLISHED off()`

**Comment by mishakim** [comment]
Update: my other virtual and real switches are only half working - I can turn them on and off, but only once, because the HomeKit state returns to On. That is, the following happens:  
(1) turn on via HomeKit, switch turns on, rules trigger; 
(2) turn off via HomeKit, switch turns off, HomeKit shows it turning right back on (but it stays off in reality/SmartThings) 
or (2a) turn off via SmartThings, HomeKit state remains "on"; 
(3) hit "on" again in HomeKit apps (Eve and iDevices), nothing happens, 
but (4) tell Siri to turn it on, HomeKit sends the on command to SmartThings and switch turns on

**Comment by rickybloomfield** [comment]
I can verify that the behavior is also happening to me. It actually flips back-and-forth between Off and On a couple times before landing on On (even though it's actually Off). I can still turn it Off and On again to get it to come on, but it didn't used to behave this way.

I can also confirm that this behavior happens when using the Apple HomeKit sample app provided via the developer program, so it's not a quirk of the Eve app.

**Comment by pdlove** [comment]
Try this with what I just published. Somewhere along the way, the program quit writing the device update to the accessory. I'm not wanting to release this to npm just yet because I expect tonight or tomorrow to have my release with the near-instant update to HomeKit.

**Comment by rickybloomfield** [comment]
That seems to fix it!

**Comment by mishakim** [comment]
same here. I have one switch that seemed to still not update, but that's because it does the same thing in SmartThings app -- have to pull a refresh to see that it has turned off. Once I updated it in SmartThings, it also updated in HomeKit. Switches that are turned off by Rule Machine rules updated instantly in HomeKit.

question - this is the first time I've modified an npm-managed package manually. Will npm update overwrite with the next release?
