### ISSUE TITLE
Error after upgrading to 0.4.0 SmartApp

### ISSUE THREAD

**Issue by kdanthony** [pdlove/homebridge-smartthings#36]
Getting "physicalgraph.exception.NotFoundException: Page Not Found" when trying to install in the simulator and the smartapp will no longer open in the IOS app to configure after upgrading to 0.4.0.

**Comment by tonesto7** [comment]
it's because he switched from state.accessToken to atomicState.accessToken.  
Atomicstate is not necessary in this use case... Plus it hasn't been working on any of my new apps lately.

**Comment by tonesto7** [comment]
actually it's because its spelled incorrectly.  If you replace `atomicstate.accessToken` with  `atomicState.accessToken` it will work correctly

**Comment by pdlove** [comment]
I'm sorry, I meant to switch back to state. atomicState didn't fix the issue I was having with state. I was having an issue where if I was executing a get on the API, updates would not get applied to the array.
I had intended to make a call and let it hang there until there was new data so the plugin wouldn't have to continually poll, but it doesn't look like that is possible.

I'm making one more update on it that should be my last update to the smart app for a long while.
Again, I promise I will not make any more major changes to the app after today.

**Comment by pdlove** [comment]
I've corrected this.

**Comment by patrickkettner** [comment]
FWIW, I am still getting this same error when attempting to install the smartapp

**Comment by patrickkettner** [comment]
apologizes - I had not enabled OAuth on the app. my mistake
